name: SmartInvs
version: 1.3.0
description: Inventory API for your Bukkit Plugins.
authors:
  - MinusKube
  - MrManHD
api-version: 1.19
website: https://github.com/TryHubDE/SmartInvs
main: fr.minuskube.inv.SmartInvsPlugin